# src/ingestion/raw_loader.py

from pydantic import BaseModel, Field, validator
from typing import Any, Dict, Optional


class RawIngestionPayload(BaseModel):
    """
    Input schema for raw biomarker ingestion.

    This schema strictly validates:
    - user identity
    - sample metadata
    - raw biomarker dictionary (float/str/None values)
    - optional additional metadata

    Note:
    - trace_id MUST NOT be provided by client (generated in ingestion layer)
    - sample_id MUST be provided by client
    """

    user_id: str = Field(..., min_length=1, description="Unique user identifier")
    sample_id: Optional[str] = Field(None, description="Unique sample request identifier")

    # IMPORTANT: Clients must NOT send trace_id
    trace_id: Optional[str] = Field(None, description="Must NOT be provided. Generated internally by ingestion pipeline.",)

    biomarkers: Dict[str, Any] = Field(..., description="Dictionary of raw biomarker names and values")

    metadata: Optional[Dict[str, Any]] = Field(None, description="Additional context such as age/sex/lab info")

    # --------------------------
    # Validators
    # --------------------------

    @validator("biomarkers")
    def ensure_non_empty_biomarkers(self, v):
        if not v:
            raise ValueError("biomarkers cannot be empty")
        return v

    @validator("trace_id")
    def forbid_trace_id(self, v):
        if v is not None:
            raise ValueError(
                "trace_id must NOT be provided in input payload. It is generated by ingestion."
            )
        return v

    @validator("sample_id")
    def forbid_trace_id(self, v):
        if v is not None:
            raise ValueError(
                "'sample_id' must be be provided in input payload."
            )
        return v
